### ISSUE TITLE
Embedded Type1 fonts not recognized as such

### ISSUE THREAD

**Issue by gollux** [veraPDF/veraPDF-library#742]
Hello!

When validating PDF files produced by LaTeX (with the pdfx package) against PDF/A-2u rules, veraPDF complains that a font is not embedded:

          <rule specification="ISO 19005-2:2011" clause="6.2.11.4" testNumber="1" status="failed" passedChecks="0" failedChecks="2">
            <description>The font programs for all fonts used for rendering within a conforming file shall be embedded within that file, as defined in ISO 32000-1:2008, 9.9.</description>
            <object>PDFont</object>
            <test>Subtype == "Type3" || Subtype == "Type0" || renderingMode == 3 || fontFile_size == 1</test>
            <check status="failed">
              <context>root/document[0]/pages[7](151 0 obj PDPage)/contentStream[0](152 0 obj PDContentStream)/operators[25]/font[0](JTVUHA+LMMathItalic12-Regular)</context>
            </check>
            <check status="failed">
              <context>root/document[0]/pages[7](151 0 obj PDPage)/contentStream[0](152 0 obj PDContentStream)/operators[13]/font[0](VJSADU+LMMathSymbols10-Regular)</context>
            </check>
          </rule>

However, brief inspection of the PDF reveals that the font is embedded, but it is a Type 1 font, which is not covered by the rule.

Unfortunately, I do not have a full PDF/A standard at hand, so I am not really sure that Type 1 is allowed here. Could you please shed more light on this issue?

**Comment by gollux** [comment]
Sorry, I forgot to add that I am using the latest shapshot of veraPDF and if you need an example of a PDF exhibiting this issue, feel free to ask.

**Comment by shem-sergey** [comment]
Hello!
Type 1 font are allowed of course, so either font is not correctly embedded or there is an error in veraPDF.
Could you please provide us with a test file so we can investigate the problem?

**Comment by gollux** [comment]
Here is one such example:
http://mj.ucw.cz/tmp/verapdf-test1.pdf

**Comment by shem-sergey** [comment]
There was a problem in veraPDF parser, it was fixed in PR https://github.com/veraPDF/veraPDF-parser/pull/220.

**Comment by gollux** [comment]
I just tried veraPDF 1.10.6 and it seems that the bug is still present.

Please see http://mj.ucw.cz/tmp/sablona-prace.pdf for a test case.

**Comment by THausherr** [comment]
Same with 1.28.1, however when I open the file with PDFBox I get an error message: "Can't read the embedded Type1 font Helvetica
    java.io.IOException: Start marker missing". The stack trace shows it's reading a PFB file which isn't correct https://issues.apache.org/jira/browse/PDFBOX-2607

**Comment by MaximPlusov** [comment]
@velikovmartin The failed validation rule for your PDF file is not the veraPDF issue. 
veraPDF reports the warning `Type 1 fonts in PFB format are not permitted` that explains the reason of the failed check.
